//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class DniPrzyjecs
    {
        public int ID { get; set; }
        public Nullable<System.Guid> Lekarz_IdLekarza { get; set; }
        public System.DateTime CzasDataRozpoczecia { get; set; }
        public System.DateTime CzasZakonczenia { get; set; }
    
        public virtual Lekarzs Lekarzs { get; set; }
    }
}
