//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaChorobies
    {
        public HistoriaChorobies()
        {
            this.Wizytas = new HashSet<Wizytas>();
        }
    
        public string Pesel { get; set; }
        public System.Guid IdLekarza { get; set; }
        public string OpisChoroby { get; set; }
        public System.DateTime OstatniaModyfikacjaOpisuChoroby { get; set; }
        public string ChorobaZeSpisu_NazwaChoroby { get; set; }
    
        public virtual Lekarzs Lekarzs { get; set; }
        public virtual Pacjents Pacjents { get; set; }
        public virtual SpisChorbs SpisChorbs { get; set; }
        public virtual ICollection<Wizytas> Wizytas { get; set; }
    }
}
