//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lekarzs
    {
        public Lekarzs()
        {
            this.DniPrzyjecs = new HashSet<DniPrzyjecs>();
            this.HistoriaChorobies = new HashSet<HistoriaChorobies>();
        }
    
        public System.Guid IdLekarza { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Adres { get; set; }
        public Nullable<System.Guid> Specjalizacja_IdSpecjalizacji { get; set; }
    
        public virtual ICollection<DniPrzyjecs> DniPrzyjecs { get; set; }
        public virtual ICollection<HistoriaChorobies> HistoriaChorobies { get; set; }
        public virtual Specjalizacjas Specjalizacjas { get; set; }
    }
}
