//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leks
    {
        public System.Guid IdLeku { get; set; }
        public int StopienRefundacji { get; set; }
        public string Dawka { get; set; }
        public string Przyjmowanie { get; set; }
        public Nullable<System.Guid> Recepta_IdRecepty { get; set; }
        public string SpisLekow_NazwaLeku { get; set; }
    
        public virtual Receptas Receptas { get; set; }
        public virtual SpisLekows SpisLekows { get; set; }
    }
}
