//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrzychodniaDBEntities2 : DbContext
    {
        public PrzychodniaDBEntities2()
            : base("name=PrzychodniaDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<DniPrzyjecs> DniPrzyjecs { get; set; }
        public DbSet<HistoriaChorobies> HistoriaChorobies { get; set; }
        public DbSet<Lekarzs> Lekarzs { get; set; }
        public DbSet<Leks> Leks { get; set; }
        public DbSet<Pacjents> Pacjents { get; set; }
        public DbSet<Receptas> Receptas { get; set; }
        public DbSet<Specjalizacjas> Specjalizacjas { get; set; }
        public DbSet<SpisChorbs> SpisChorbs { get; set; }
        public DbSet<SpisLekows> SpisLekows { get; set; }
        public DbSet<Uzytkowniks> Uzytkowniks { get; set; }
        public DbSet<Wizytas> Wizytas { get; set; }
    }
}
