//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receptas
    {
        public Receptas()
        {
            this.Leks = new HashSet<Leks>();
        }
    
        public System.Guid IdRecepty { get; set; }
        public System.DateTime CzasWystawienia { get; set; }
        public Nullable<System.Guid> Wizyta_IdWizyty { get; set; }
    
        public virtual ICollection<Leks> Leks { get; set; }
        public virtual Wizytas Wizytas { get; set; }
    }
}
