//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpisLekows
    {
        public SpisLekows()
        {
            this.Leks = new HashSet<Leks>();
        }
    
        public string NazwaLeku { get; set; }
        public string NazwaPolskaLeku { get; set; }
    
        public virtual ICollection<Leks> Leks { get; set; }
    }
}
