//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wizytas
    {
        public Wizytas()
        {
            this.Receptas = new HashSet<Receptas>();
        }
    
        public System.Guid IdWizyty { get; set; }
        public System.DateTime Data { get; set; }
        public System.TimeSpan CzasWizyty { get; set; }
        public string HistoriaChoroby_Pesel { get; set; }
        public Nullable<System.Guid> HistoriaChoroby_IdLekarza { get; set; }
        public string Opis { get; set; }
        public bool CzyOdbyta { get; set; }
    
        public virtual HistoriaChorobies HistoriaChorobies { get; set; }
        public virtual ICollection<Receptas> Receptas { get; set; }
    }
}
